
version: 2

models:
    - name: pv_count
      description: "A starter dbt model"
      columns:
          - name: event_date
            description: "The primary key for this table"
            tests:
                - not_null

    - name: page_pv
      description: "A starter dbt model"
      columns:
          - name: event_date
            description: "The primary key for this table"
            tests:
                - not_null
