
version: 2

models:
    - name: pv_count
      description: "A starter dbt model"
      columns:
          - name: user_pesdo_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: event_*
      description: "A starter dbt model"
      columns:
          - name: event_date
            description: "The primary key for this table"
            tests:
                - not_null
